spring.application.name=smart-parking

spring.datasource.url=jdbc:postgresql://db.rzzybbvekcvcaaddzrrz.supabase.co:6543/postgres?pgbouncer=true
spring.datasource.username=postgres
spring.datasource.password=SmartParkingSystemG6

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.client.registration.google.client-id=416974225540-rrv21bk4qkcfpgbs8rnigjdktcudmaq9.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=CLIENT_SECRET_CUA_BAN
spring.security.oauth2.client.registration.google.scope=openid,email,profile