spring.application.name=smart-parking

spring.datasource.url=jdbc:postgresql://db.rzzybbvekcvcaaddzrrz.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=SmartParkingSystemG6

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect